# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    ehrOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *centAuth
                    - *clinician
                    - *radioLogist
                    - *pharmacist
                    - *healthCareProvider
                    - *researcher

    ehrOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *centAuth
                    - *clinician
                    - *radioLogist
                    - *pharmacist
                    - *healthCareProvider
                    - *researcher

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/ehr.com/msp

    - &centAuth 
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: centAuthMSP

        # ID to load the MSP definition as
        ID: centAuthMSP

        MSPDir: crypto-config/peerOrganizations/centAuth.ehr.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.centAuth.ehr.com
              Port: 7051
    - &clinician
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: clinicianMSP

        # ID to load the MSP definition as
        ID: clinicianMSP

        MSPDir: crypto-config/peerOrganizations/clinician.ehr.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.clinician.ehr.com
              Port: 7051
    - &radioLogist
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: radioLogistMSP

        # ID to load the MSP definition as
        ID: radioLogistMSP

        MSPDir: crypto-config/peerOrganizations/radioLogist.ehr.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.radioLogist.ehr.com
              Port: 7051

    - &pharmacist 
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: pharmacistMSP

        # ID to load the MSP definition as
        ID: pharmacistMSP

        MSPDir: crypto-config/peerOrganizations/pharmacist.ehr.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.pharmacist.ehr.com
              Port: 7051

    - &researcher
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: researcherMSP

        # ID to load the MSP definition as
        ID: researcherMSP

        MSPDir: crypto-config/peerOrganizations/researcher.ehr.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.researcher.ehr.com
              Port: 7051

    - &healthCareProvider
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: healthCareProviderMSP

        # ID to load the MSP definition as
        ID: healthCareProviderMSP

        MSPDir: crypto-config/peerOrganizations/healthCareProvider.ehr.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.healthCareProvider.ehr.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.ehr.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
